# Site settings
title: The life and times of Mobile Tester
email: evanniedojadlo@gmail.com
baseurl: ""
url: "http://mobiletester.me"
twitter_username: eniedojadlo
github_username:  evanniedojadlo

# Build settings
markdown: kramdown
permalink: pretty
