# Site settings
title: Makersquare Cohort 3 - Blog
email: evanniedojadlo@gmail.com
description: "Makersquare Cohort 3 - Front End Development blog"
baseurl: ""
url: "http://mobiletester.me"
twitter_username: evanniedojadlo
github_username:  evanniedojadlo

# Build settings
markdown: kramdown
permalink: pretty
