# Site settings
title: A personal collection of Software Guides and Discovery from a Lifelong learner
email: evanniedojadlo@gmail.com
baseurl: ""
url: "http://mobiletester.me"
twitter_username: eniedojadlo
github_username:  evanniedojadlo

# Build settings
markdown: kramdown
permalink: pretty
